server.port: 8080
management:
  endpoint.health.probes.enabled: true
  health:
    livenessState:
      enabled: true
    readinessState:
      enabled: true

open-weather:
  api-key: <change-me>

config-cat:
  turned-off: true
  interval: 300
  key: <change-me>
  flags:
    isFooEnabled: false
