@startuml
skinparam ConditionEndStyle hline
skinparam defaultTextAlignment center
start

    partition "GitHub Actions" {
        fork
        :Vienetų ir komponentų testų vykdymas;
        fork again
        :Artefakto kūrimas;
        fork again
        :Statinės analizės vykdymas, pasinaudojant įrankiu SonarCloud;
        end fork
        :Artefakto Docker atvaizdo kūrimas;
        :Priėmimo testų vykdymas;
    }

stop
@enduml