name: Deployment To Production Environment

on:
  push:
    tags:
      - '*'
  workflow_run:
    workflows: [ "Push to branches workflow" ]
    branches: [ main ]
    types:
      - completed

jobs:
  deploy:
    name: Deploy to Production Environment
    runs-on: ubuntu-latest
    if: contains('refs/heads/main', github.ref)
    needs: build
    steps:
      - uses: actions/checkout@v2
        with:
          # Shallow clones should be disabled for a better relevancy of analysis
          fetch-depth: 0
      - name: Set release version
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Test
        run: |
          echo $RELEASE_VERSION
          echo ${{ env.RELEASE_VERSION }}
      - name: Deploy to Test environment
        run: echo "Deploy to Test Environment with tag ${{ env.RELEASE_VERSION }}"