# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Push to branches workflow

on:
  push:
    branches:
      - '**'
    tags:
      - '*'

jobs:

  build:
    name: Build and Analize
    runs-on: ubuntu-latest
    env:
      DOCKER_REPO_NAME: cd-pipeline-app
      PROJECT_ID: ${{ secrets.GKE_PROJECT }}
    steps:
      - uses: actions/checkout@v2
        with:
          # Shallow clones should be disabled for a better relevancy of analysis
          fetch-depth: 0
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Cache Gradle packages
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle
      - name: Cache SonarCloud packages
        uses: actions/cache@v1
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: Build and analyze
        run: ./gradlew build jacocoTestReport sonarqube --info
        env:
          # Needed to get some information about the pull request, if any
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # SonarCloud access token should be generated from https://sonarcloud.io/account/security/
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      - name: Retrieve Docker image tag value
        run: echo "DOCKER_IMAGE_TAG=$(git describe --tag)" >> $GITHUB_ENV
        id: git_describe
      - name: Extract Branch Name
        run: echo "BRANCH=$(echo ${GITHUB_REF##*/})" >> $GITHUB_ENV
      # Setup gcloud CLI
      - uses: google-github-actions/setup-gcloud@v0.2.0
        if: ${{ env.BRANCH == 'main' }}
        with:
          service_account_key: ${{ secrets.GKE_SA_KEY }}
          project_id: ${{ secrets.GKE_PROJECT }}

      # Configure docker to use the gcloud command-line tool as a credential helper
      - name: Configure GCloud Docker
        if: ${{ env.BRANCH == 'main' }}
        run: |-
          gcloud --quiet auth configure-docker


      - name: Build and tag Docker image
        run: |
          ./gradlew dockerBuildImage
          docker tag mila973/cd-pipeline-app:latest gcr.io/$PROJECT_ID/$DOCKER_REPO_NAME:$DOCKER_IMAGE_TAG
      - name: Execute Acceptance Testing
        run: ./acceptance-tests/gradlew test
      - name: Publish
        if: ${{ env.BRANCH == 'main' }}
        run: |-
          docker push "gcr.io/$PROJECT_ID/$DOCKER_REPO_NAME:$DOCKER_IMAGE_TAG"
    outputs:
      docker_image_tag: ${{ env.DOCKER_IMAGE_TAG }}


  deploy-test:
    name: Deploy to Test Environment
    runs-on: ubuntu-latest
    if: contains('refs/heads/main', github.ref) || (github.event_name == 'push' && contains(github.ref, '/tags/'))
    needs: build
    env:
      GKE_CLUSTER: cluster-1
      GKE_ZONE: europe-central2-a
    steps:
      - uses: actions/checkout@v2
        with:
          # Shallow clones should be disabled for a better relevancy of analysis
          fetch-depth: 0
      - name: Deploy to Test environment
        run: echo "Deploy to Test Environment with tag ${{ needs.build.outputs.docker_image_tag }}"
      # Get the GKE credentials so we can deploy to the cluster
      - uses: google-github-actions/get-gke-credentials@v0.2.1
        with:
          cluster_name: ${{ env.GKE_CLUSTER }}
          location: ${{ env.GKE_ZONE }}
          credentials: ${{ secrets.GKE_SA_KEY }}
      - uses: azure/setup-helm@v1
        with:
          version: v3.0.1
        id: install
      - name: Deploy to Test environment
        run: |
          chmod +x "./k8s/deploy.sh"
          ./k8s/deploy.sh --set image.tag=${{ needs.build.outputs.docker_image_tag }} --namespace="test" --wait --timeout 10m

  deploy-prod:
    name: Deploy to Production Environment
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && contains(github.ref, '/tags/')
    needs: [build, deploy-test]
    steps:
      - uses: actions/checkout@v2
        with:
          # Shallow clones should be disabled for a better relevancy of analysis
          fetch-depth: 0
      - name: Set release version
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
      - name: Test
        run: |
          echo $RELEASE_VERSION
          echo ${{ env.RELEASE_VERSION }}
      # Get the GKE credentials so we can deploy to the cluster
      - uses: google-github-actions/get-gke-credentials@v0.2.1
        with:
          cluster_name: ${{ env.GKE_CLUSTER }}
          location: ${{ env.GKE_ZONE }}
          credentials: ${{ secrets.GKE_SA_KEY }}
      - uses: azure/setup-helm@v1
        with:
          version: v3.0.1
        id: install
      - name: Deploy to Production environment
        run: |
          chmod +x "./k8s/deploy.sh"
          ./k8s/deploy.sh --set image.tag=$RELEASE_VERSION --namespace="prod" --wait --timeout 10m




