name: Rollback deployment

on:
  workflow_dispatch:
    inputs:
      tag:
        required: true
        description: 'Desired version for rollback'

jobs:
  rollback:
    name: Deploy to Production Environment
    runs-on: ubuntu-latest
    env:
      GKE_CLUSTER: cluster-1
      GKE_ZONE: europe-central2-a
      CONFIG_CAT_KEY: ${{ secrets.CONFIG_CAT_KEY_PROD }}
      OPEN_WEATHER_API_KEY: ${{ secrets.OPEN_WEATHER_API_KEY }}
      DOCKER_REPO_NAME: cd-pipeline-app
      PROJECT_ID: ${{ secrets.GKE_PROJECT }}
      IMAGE_TAG: ${{ github.event.inputs.tag }}
    steps:
      - uses: google-github-actions/get-gke-credentials@v0.2.1
        with:
          cluster_name: ${{ env.GKE_CLUSTER }}
          location: ${{ env.GKE_ZONE }}
          credentials: ${{ secrets.GKE_SA_KEY }}
      - run: |
          echo "Tags: ${{ github.event.inputs.tag }}"
      - uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          service_account_key: ${{ secrets.GKE_SA_KEY }}
          project_id: ${{ secrets.GKE_PROJECT }}

      - name: Configure GCloud Docker
        run: |-
          gcloud --quiet auth configure-docker
      - run: |
          docker pull gcr.io/$PROJECT_ID/$DOCKER_REPO_NAME:$IMAGE_TAG


